# Generated by Django 3.1.5 on 2021-01-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210116_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_promotions',
            field=models.BooleanField(default=False),
        ),
    ]
